eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
okta:
  ouath2:
    issuer: https://dev-4uahaqfo4t52rnu0.us.auth0.com
    audiences: https://dev-4uahaqfo4t52rnu0.us.auth0.com/api/v2/
